export const GET_LIST_POST = "GET_LIST_POST";
export const GET_LIST_POST_SUCCESS = "GET_LIST_POST_SUCCESS";
export const POST_FETCH_SUCCEEDED = "POST_FETCH_SUCCEEDED";
export const POST_FETCH_FAILED = "POST_FETCH_FAILED";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";
export const GET_USERS = "GET_USERS";

export const ADD_COMMENT = "ADD_COMMENT";
